language: node_js
node_js:
  - "20"

cache:
  directories:
    - node_modules

before_install:
  - export NG_CLI_VERSION=$(node -p "require('./package.json').devDependencies['@angular/cli']")
  - npm install -g @angular/cli@$NG_CLI_VERSION

install:
  - npm install

script:
  - npm run lint
  - npm test
